name: Build

on:
- push
- pull_request

jobs:
  build:
    env:
      RANDOMX_VERSION: v1.1.9
    strategy:
      matrix:
        # CHECK: When you change the below list, you need to change
        # the "download-artifact" steps in the "pack" job.
        os: [macos-10.15, ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - if: startsWith(github.ref, 'refs/tags/')
      shell: pwsh
      run: |
        $proj = "./RandomXSharp/RandomXSharp.csproj"
        $xpath = '/Project/PropertyGroup/VersionPrefix/text()'
        $projVer = (Select-Xml -Path "$proj" -XPath $xpath).Node.Value
        echo "VersionPrefix: $projVer"
        $tagVer = $env:GITHUB_REF.Substring(10)
        echo "tag: $tagVer"
        exit ($tagVer -eq $projVer ? 0 : 1)
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - uses: actions/cache@v2
      with:
        path: native
        key: ${{ runner.os }}-${{ env.RANDOMX_VERSION }}
    - if: runner.os == 'Linux'
      run: sudo apt-get install -y build-essential gcc gdb lldb
    - if: runner.os != 'Windows'
      run: ./build-librandomx.sh "$RANDOMX_VERSION"
    - if: runner.os == 'Windows'
      run: ./Build-RandomX.ps1 -RandomXVersion "${env:RANDOMX_VERSION}"
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ runner.os }}-nuget-
    - run: dotnet restore
    - run: dotnet build --no-restore
    - run: dotnet test --no-build --verbosity normal
    - if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: native-${{ runner.os }}
        path: |
          native/**/*.dll
          native/**/*.dylib
          native/**/*.so
        if-no-files-found: error
        retention-days: 7

  dist:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    # Download all native-* artifacts made by the "build" job.
    - uses: actions/download-artifact@v2
      with:
        name: native-Linux
        path: native
    - uses: actions/download-artifact@v2
      with:
        name: native-macOS
        path: native
    - uses: actions/download-artifact@v2
      with:
        name: native-Windows
        path: native
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: nuget-
    - run: |
        if [[ "$GITHUB_REF" = refs/tags/* ]]; then
          dotnet pack -c Release -o dist
        else
          dotnet pack \
            -c Release \
            --version-suffix="dev.$GITHUB_RUN_NUMBER+${GITHUB_SHA:0:7}" \
            -o dist
        fi
    - name: Check if native libraries are correctly placed
      run: |
        set -e
        7z l dist/*.nupkg > /tmp/nupkg-files.txt
        grep runtimes/linux/native/librandomx.so  /tmp/nupkg-files.txt
        grep runtimes/osx/native/librandomx.dylib /tmp/nupkg-files.txt
        grep runtimes/win7-x64/native/randomx.dll /tmp/nupkg-files.txt
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*.nupkg
        if-no-files-found: error
    - if: '!github.event.repository.fork'
      run: |
        dotnet nuget push \
          dist/*.nupkg \
          --api-key "${{ secrets.NUGET_API_KEY }}" \
          --source https://api.nuget.org/v3/index.json
